-- Create a profiles table if it doesn't exist
CREATE TABLE IF NOT EXISTS profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id),
  name TEXT,
  dob DATE,
  gender TEXT,
  language TEXT DEFAULT 'en',
  trial_start_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  is_subscribed BOOLEAN DEFAULT FALSE,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable Row Level Security if not already enabled
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

-- Create policies (using DO blocks to avoid "already exists" errors)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'profiles' AND policyname = 'Public profiles are viewable by everyone.'
    ) THEN
        CREATE POLICY "Public profiles are viewable by everyone."
          ON profiles FOR SELECT
          USING ( true );
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'profiles' AND policyname = 'Users can insert their own profile.'
    ) THEN
        CREATE POLICY "Users can insert their own profile."
          ON profiles FOR INSERT
          WITH CHECK ( auth.uid() = id );
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'profiles' AND policyname = 'Users can update own profile.'
    ) THEN
        CREATE POLICY "Users can update own profile."
          ON profiles FOR UPDATE
          USING ( auth.uid() = id );
    END IF;
END
$$;

-- Create a table for messages if it doesn't exist
CREATE TABLE IF NOT EXISTS messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id),
  role TEXT CHECK (role IN ('user', 'assistant')),
  content TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE messages ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'messages' AND policyname = 'Users can view their own messages.'
    ) THEN
        CREATE POLICY "Users can view their own messages."
          ON messages FOR SELECT
          USING ( auth.uid() = user_id );
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'messages' AND policyname = 'Users can insert their own messages.'
    ) THEN
        CREATE POLICY "Users can insert their own messages."
          ON messages FOR INSERT
          WITH CHECK ( auth.uid() = user_id );
    END IF;
END
$$;
